# Generated by Django 4.2 on 2025-06-22 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question_types', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('options', models.JSONField()),
                ('correct_answer', models.JSONField()),
                ('explanation', models.TextField(blank=True, null=True)),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.TextField()),
                ('courses', models.JSONField()),
                ('roles', models.JSONField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('question_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='question_types.questiontype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
