from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import QuestionViewSet

router = DefaultRouter()
router.register('questions', QuestionViewSet, basename='questions')

urlpatterns = [
    path('', include(router.urls)),
    # The following paths are automatically generated by the @action decorators
    # and included in router.urls:
    # - 'questions/user/'
    # - 'questions/student/'
]
