# Generated by Django 4.2.23 on 2025-07-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('questions_attend', models.PositiveIntegerField()),
                ('correct_answer', models.PositiveIntegerField()),
                ('percentage', models.FloatField()),
                ('is_pass', models.BooleanField()),
            ],
        ),
    ]
