# Generated by Django 4.2 on 2025-07-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='correct_answer',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='questions_attend',
            field=models.IntegerField(),
        ),
    ]
