# Generated by Django 4.2.23 on 2025-06-16 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        ('demo', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demosession',
            name='guest',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demo_session', to='users.guestprofile'),
        ),
        migrations.AddField(
            model_name='demoanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.question'),
        ),
        migrations.AddField(
            model_name='demoanswer',
            name='selected_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.answer'),
        ),
        migrations.AddField(
            model_name='demoanswer',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='demo.demosession'),
        ),
        migrations.AlterUniqueTogether(
            name='demoanswer',
            unique_together={('session', 'question')},
        ),
    ]
